<style type="text/css">
.list-row {
	border-bottom: 1px solid #ccc;
	width: 187px;
	padding: 4px;
	background: #FFF;
}

.listrow-header {
	margin-bottom: 5px;
	cursor: pointer;
	padding: 4px;
	background: #B5D9E5;
}

.col {
	width: 83px;
	display: inline-block;
	vertical-align: top;
}

.col-large {
	width: 166px;
}

.actor-list-row-1:hover {
	cursor: pointer
}
</style>

<script type="text/javascript">

$(document).ready(function(){
  $('.actor-list-row-1').click(function(){
    $('#actor-details-popup').load('/actor/view', { actor_id: $(this).attr('id') });
  });

  $('.close-used-in').click(function(){
      $('#actor-details-used-in').hide();
  });

});
</script>

<div class="listrow" style="margin: 0 5px 1px;">
	<span>Matter Dependencies</span> <span
		class="close-used-in ui-icon ui-icon-close" style="float: right;"
		title="Close"></span>
	<div class="list-row">
		<div class="col">Ref</div>
		<div class="col">Role</div>
	</div>
	<div style="width: 210px; height: 200px; overflow: auto">
<?php 
$type = '';
$close_type = 0;
$add_empty_row = 0;

foreach($this->matter_dependencies as $matter){
?>
<div class="list-row">
			<div class="col">
				<a href="/matter/view/id/<?= $matter['id']?>" target="_blank"><?= $matter['UID']?></a>
			</div>
			<div class="col"><?= $matter['role']?></div>
		</div>
<?php } ?>
	</div>
</div>

<div class="listrow">
	<span>Other Actor Dependencies</span> 
	<span class="close-used-in ui-icon ui-icon-close" style="float: right;" title="Close"></span>
	<div class="list-row">
		<div class="col">Actor</div>
		<div class="col">Dependency</div>
	</div>
	<div style="width: 210px; height: 200px; overflow: auto">
<?php 
$type = '';
$close_type = 0;
$add_empty_row = 0;

foreach($this->other_actor_dependencies as $actor){
?>
<div class="list-row">
			<div class="col actor-list-row actor-list-row-1" id="<?=$actor['id']?>">
				<?php echo htmlentities($actor['Actor'])?>
			</div>
			<div class="col "><?php echo htmlentities($actor['Dependency'])?></div>
		</div>
<?php } ?>
	</div>
</div>

