<style type="text/css">
#home-left{
    width:auto;
    float:left;
    margin: 10px 0px;
}
.phpip-list{
    margin:0px 5px 5px;
    padding: 4px;
    float:left;
    background: #B5D9E5;
    display:block;
    -moz-border-radius: 0px 4px 4px 4px;
    -webkit-border-radius: 0px 4px 4px 4px;
    -moz-box-shadow: 2px 2px 1px #888888;
    -webkit-box-shadow: 2px 2px 1px #888888;
    max-height:270px;
    overflow:auto;
}
.phpip-list li{
    list-style: none;
    padding: 3px 6px;
    color: #3F3F38;
    border-bottom: 1px solid #DDD;
    background: #FFF;
}
.phpip-list li:hover {
    background: #C8E8F3;
}
.phpip-list li:first-child {
    background: #1E4262;
    color: #FFF;
    -moz-border-radius: 4px 4px 0 0;
    -webkit-border-radius: 4px 4px 0 0;
    border: none;
}
.phpip-list li:last-child {
    -moz-border-radius: 0 0 4px 4px;
    -webkit-border-radius: 0 0 4px 4px;
}
#home-right{
    float: left;
    width: auto;
}
#open-tasks-list{
    max-height: 270px;
    width: 540px;
    overflow-x: hidden;
    overflow: auto;
}
#ren-tasks-list{
    max-height: 270px;
    width: 540px;
    overflow-x: hidden;
    overflow: auto;
}
#users-task-count{
    width: 387px;
}
.col-cat{
    display:inline-block;
    width: 150px;
}
.col-code{
    display:inline-block;
    width: 75px;
}
.col-count{
    display:inline-block;
    width: 100px;
    text-align: right;
}
.col-actions{
    display: inline-block;
    width: 50px;
    text-align: center;
}
.col-task-name{
   display: inline-block;
   width: 200px;
}
.col-task-matter{
   display: inline-block;
   width: 150px;
}
.col-task-due_date{
  display: inline-block;
  width: 100px;
}
.img-buttons{
  border: none;
}
.col-user-login{
  display: inline-block;
  width: 120px;
}
.col-open-count{
  display: inline-block;
  width: 75px;
  text-align: center;
}
.col-most-urgent{
  display: inline-block;
  width: 135px;
  text-align: right;
}
#task-pop-up{
  display: none;
  z-index: 101;
  width:auto;
  top: 200px;
  position:fixed;
}
#add-matter-popup{
  display: none;
  z-index: 101;
  width:auto;
  top: 200px;
  position:fixed;
}
.list-header{
  background: #B5D9E5;
  float:left;
  margin-left: 5px;
  -moz-border-radius: 4px 4px 0px 0px;
  -webkit-border-radius: 4px 4px 0px 0px;
  width:auto;
  padding: 5px 5px;
  display:block; 
}
.home-box{
  float:left;
}
#clear-task-name{
padding: 5px;
font-size: 13px;
font-weight: bold;
text-align: center;
display: block;
}
.clear-tasks-box{
  background: #B5D9E5;
  padding: 4px 5px 0px;
  float:right;
  margin:-3px 20px 0px 0px;
  -moz-border-radius: 4px 4px 0px 0px;
  -webkit-border-radius: 4px 4px 0px 0px;
  height:24px;
}
.done-date{
  width: 100px;
  border: 1px inset #ccc;
}
</style>

<link href="/js/css/smoothness/jquery-ui-1.8.12.custom.css" media="screen" rel="stylesheet" type="text/css" >
<script type="text/javascript">
$(document).ready(function(){
    $('.open-task').click(function(){
       var tid = $(this).attr('id');
       $('#facade').css('height', $(document).height());
       $('#facade').css("display", "block");
       $.ajax({
         url: '/index/open-task-details',
         type: 'GET',
         data: { task_id: tid },
         success: function(data){
             $('#task-pop-up').html(data);
             var ren_left = Math.round($(window).width()/2) - Math.round($('#task-pop-up').width()/2);
             $('#task-pop-up').css('left', ren_left);
             $('#task-pop-up').css('display', 'block');
         }
       });
    });
    $('.add-cat-matter').click(function(){
        var catid = $(this).attr('id');
        $('#facade').css('height', $(document).height());
        $('#facade').css("display", "block");
        $.ajax({
          url: '/matter/add',
          type: 'GET',
          data: { category_id : catid },
          success: function(data){
             $('#add-matter-popup').html(data);
             var ren_left = Math.round($(window).width()/2) - Math.round($('#add-matter-popup').width()/2);
             $('#add-matter-popup').css('left', ren_left);
             $('#add-matter-popup').css('display', 'block');
          }
        });
    });

    $('.done-date').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'dd/mm/yy',
//        minDate: 0,
    });

    $('#clear-open-tasks').click(function(){
        var tids = new Array();
        $('.clear-open-task').each(function(){
          if($(this).is(':checked'))
             tids.push($(this).attr('id'));
        });
        $.ajax({
          url: '/matter/clear-tasks',
          type: 'POST',
          data: { task_ids: tids, done_data: $('#open-done-date').val() },
          success:function(data){
            location.reload();
          }
        });
    });

    $('#clear-ren-tasks').click(function(){
        var tids = new Array();
        $('.clear-ren-task').each(function(){
          if($(this).is(':checked'))
             tids.push($(this).attr('id'));
        });
        $.ajax({
          url: '/matter/clear-tasks',
          type: 'POST',
          data: { task_ids: tids, done_data: $('#ren-done-date').val() },
          success:function(data){
            location.reload();
          }
        });
    });

    $('#cancel-clear-task').click(function(){
        $('.flake-dialog').css('display', 'none');
        $('#facade').css("display", "none");
    });

    $('#submit-clear-task').click(function(){
        var tid = $('#clear-task-name').attr('tid');
        var done_date = $('#done-date').val();
        $.ajax({
          url: '/matter/clear-task',
          type: 'POST',
          data: { task_id: tid, done_date: done_date },
          success: function(data){
            location.reload();
          }
        }); 
        $('.flake-dialog').css('display', 'none');
        $('#facade').css("display", "none");
    });
});
</script>
<div id="home-wrap">

<div id="home-left">
<div id="categories-box" class="home-box">
<div class="list-header">Categories</div>
<div style="float:right;margin:1px 3px 0px 0px;"><a href="javascript:void(0);" class="add-cat-matter button-style" style="padding: 2px;" id="" ><img src="/images/Add-16.png" alt="+" width=14 height=14 title="Add Matter" class="img-buttons" style="vertical-align:middle;"></img> Add new matter</a></div>
<br>
<ul class="phpip-list" id="category-list">
    <li><div class="col-cat">Category</div><div class="col-code">Code</div><div class="col-count">No of matters</div><div class="col-actions"></div></li>
<?php if(count($this->categories)){ ?>
<?php foreach($this->categories as $matter): ?>
    <li><div class="col-cat"><a href=""><?=$matter['category']?></a></div><div class="col-code"><?=$matter['category_code']?></div><div class="col-count"><?=$matter['no_of_matters']?></div><div class="col-actions"><a href="javascript:void(0);" class="add-cat-matter" id="<?=$matter['category']?>-<?=$matter['category_code']?>" ><img src="/images/Add-16.png" alt="+" width=14 height=14 title="Add Matter" class="img-buttons"></img></a></div></li>
<?php endforeach; ?>
</ul>
<?php }else{ ?>
<li></li>
<?php } ?>
</div>

<div id="open-tasks-box" class="home-box">
<?php if(count($this->open_tasks)): ?>
<div class="list-header">Open tasks</div>
<div class="clear-tasks-box">
<label for="open-done-date" >Done date </label><input type="text" value="" id="open-done-date" class="done-date" /><input type="hidden" value="" id="alt-date" />
<input type="button" class="button-style" id="clear-open-tasks" value="Clear tasks" style="padding: 0px 8px;" />
</div>
<br>
<ul class="phpip-list" id="open-tasks-list">
    <li><div class="col-task-name">Task name</div><div class="col-task-matter">Matter</div><div class="col-task-due_date">Due date</div><div class="col-actions">Close</div></li>
<?php foreach($this->open_tasks as $open_task){ 
$task_name  = $open_task['task_name'];
$task_name .= ($open_task['task_detail'])?" - ".$open_task['task_detail']: "";

$matter_UID  = $open_task['caseref'];
$matter_UID .= ($open_task['country'])? " ".$open_task['country']: "";
$matter_UID .= ($open_task['origin'])? " ".$open_task['origin']: "";
$matter_UID .= ($open_task['type_code'])? " ".$open_task['type_code']: "";
?>
    <li id="<?=$open_task['task_ID']?>"><div class="col-task-name"><a href="javascript:void(0);" class="open-task" id="<?=$open_task['task_ID']?>"><?=$task_name?></a></div><div class="col-task-matter"><a href="/matter/view/id/<?=$open_task['MID']?>"><?=$open_task['UID']?></a></div><div class="col-task-due_date"><?=$open_task['due_date']?></div>
<div class="col-actions"><input type="checkbox" name="clear-task-<?=$open_task['task_ID']?>" id="<?=$open_task['task_ID']?>" class="clear-open-task" value="Clear" /></div></li>
<?php } ?>
</ul>
</div>
<?php endif; ?>
</div>

<div id="home-right" >
<div id="users-box" class="home-box">
<?php if(count($this->users_list)): ?>
<div class="list-header">Users tasks</div><br>
<ul class="phpip-list" id="users-task-count" >
    <li><div class="col-user-login">User</div><div class="col-open-count">Open Tasks</div><div class="col-most-urgent">Most urgent</div></li>
<?php foreach($this->users_list as $user){ 
if($user['no_of_tasks'] > 0){
?>
    <li><div class="col-user-login"><a href="/index/user-page/username/<?=$user['login']?>"><?=$user['login']?></a></div><div class="col-open-count"><a href="/index/user-open-tasks/username/<?=$user['login']?>"><?=$user['no_of_tasks']?></a></div><div class="col-most-urgent"><?=$user['urgent_date']?></div></li>
<?php }} ?>
</ul>
<?php endif;?>
</div>
<div id="open-renewals-box" class="home-box">
<?php if(count($this->ren_tasks)): ?>
<div class="list-header">Open renewals</div>
<div class="clear-tasks-box">
<label for="ren-done-date" >Done date </label><input type="text" value="" id="ren-done-date" class="done-date" /><input type="hidden" value="" id="alt-date" />
<input type="button" class="button-style" id="clear-ren-tasks" value="Clear tasks" style="padding: 0px 8px;" />
</div>
<br>
<ul class="phpip-list" id="ren-tasks-list">
    <li><div class="col-task-name">Task name</div><div class="col-task-matter">Matter</div><div class="col-task-due_date">Due date</div><div class="col-actions">Close</div></li>
<?php foreach($this->ren_tasks as $open_task){ 
$task_name  = $open_task['task_name'];
$task_name .= ($open_task['task_detail'])?" - ".$open_task['task_detail']: "";

$matter_UID  = $open_task['caseref'];
$matter_UID .= ($open_task['country'])? " ".$open_task['country']: "";
$matter_UID .= ($open_task['origin'])? " ".$open_task['origin']: "";
$matter_UID .= ($open_task['type_code'])? " ".$open_task['type_code']: "";
?>
 <li id="<?=$open_task['task_ID']?>"><div class="col-task-name"><a href="javascript:void(0);" class="open-task" id="<?=$open_task['task_ID']?>"><?=$task_name?></a></div><div class="col-task-matter"><a href="/matter/view/id/<?=$open_task['MID']?>"><?=$open_task['UID']?></a></div><div class="col-task-due_date"><?=$open_task['due_date']?></div>
<div class="col-actions"><input type="checkbox" name="clear-task-<?=$open_task['task_ID']?>" id="<?=$open_task['task_ID']?>" class="clear-ren-task button-style" value="Clear" /></div></li>
<?php } ?>
</ul>
<?php endif; ?>
</div>
</div>
</div>

</div>
</div>

<div id="task-pop-up" class="place-card" ></div>
<div id="add-matter-popup" class="" ></div>
<div id="facade"></div>

<div class="flake-dialog place-card" >
<div class="dialog-head"><span class="dialog-title">Clear task</span> <span class="dialog-close">X</span></div>
<div class="dialog-content">
<div style="display:block;"><span id="clear-task-name"></span></div>
<div style="display:block;"><label for="done-date" >Done date </label><input type="text" value="" id="done-date" /><input type="hidden" value="" id="alt-date" /></div>
<div style="text-align: center;"><input type="button" value="Clear task" id="submit-clear-task" class="button-style" /> <input type="button" value="Cancel" id="cancel-clear-task" class="button-style" /></div>
</div>
</div>

