<script type="text/javascript">
$(document).ready(function(){
    $('.open-task').click(function(){
    	trig_id_code = $(this).attr('id').split('-');
    	if (trig_id_code[1] == 'REN')
    		ren = 1;
    	else
    		ren = 0;
		$('#facade').show();
		$('#tasklist-pop-up').load('/matter/tasklist/event_id/' + trig_id_code[0], { renewal: ren }).show();
    });
});
</script>

<?php

foreach ( $this->open_tasks as $open_task ) {
	$task_name = $open_task ['task_name'];
	$task_name .= ($open_task ['task_detail']) ? " - " . $open_task ['task_detail'] : "";?>
<li id="<?=$open_task['task_ID']?>">
	<div class="col-task-name">
		<a href="javascript:void(0);" class="open-task" id="<?=$open_task['trigger_ID']?>-<?=$open_task['code']?>">
			<?=$task_name?>
								
		</a>
	</div>
	<div class="col-task-matter">
		<a href="/matter/view/id/<?=$open_task['MID']?>">
			<?=$open_task['UID']?>
			
		</a>
	</div>
	<div class="col-task-due_date">
		<?=$open_task['due_date']?>
		
	</div>
	<div class="col-actions">
		<input type="checkbox" name="clear-task-<?=$open_task['task_ID']?>" id="<?=$open_task['task_ID']?>" class="clear-open-task" value="Clear" />
	</div>
</li>
<?php } ?>
