<style type="text/css">
#submit-element {
	margin-left: 125px;
}

#auth_failed {
	display: block;
	color: #F00;
	font-size: 11px;
	font-weight: bold;
	text-align: center;
	margin-bottom: 10px;
}
.login-input {
        width: 180px;
        border: 1px inset #888;
        padding: 1px 2px;
        vertical-align: top;
        margin-bottom: 2px;
}

</style>
<?php
$this->loginForm->setAction ( $this->url () )->setMethod ( 'post' )->setEncType ( 'multipart/form-data' );
if (isset ( $this->auth_error )) {
	echo '<div id="auth_failed" >' . $this->auth_error . "</div>";
}?>
<form action="<?= $this->escape($this->loginForm->getAction()) ?>"
	method="<?= $this->loginForm->getMethod() ?>"
	enctype="$this->loginForm->getEncType()" accept-charset="utf-8">
<?php
echo $this->loginForm->Email;
echo $this->loginForm->Password;
echo $this->loginForm->Language;
echo $this->loginForm->submit;
?>
</form>

