<style>
.pagination{
  margin: 5px 0px;
  width:100%;
  text-align:center;
}
</style>

<div class="pagination" >    
    <div style="display:inline-block;">
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->first)); ?>">1</a> |
        <?php else: ?>
                <span class="disabled">1</span> |
        <?php endif; ?>
    
        <!-- Previous page link -->    
        <?php if (isset($this->previous)): ?>
              <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt;</a> |
        <?php else: ?>
            <span class="disabled">&lt;</span> |
        <?php endif; ?>
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
            <?php else: ?>
                <?= $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        
        <!-- Next page link -->        
        <?php if (isset($this->next)): ?>
              | <a href="<?= $this->url(array('page' => $this->next)); ?>">&gt;</a> |
        <?php else: ?>
            | <span class="disabled">&gt;</span> |
        <?php endif; ?>
        <!-- Last page link -->
        
        <?php if (isset($this->next)): ?>
              <a href="<?= $this->url(array('page' => $this->last)); ?>"><?= $this->last; ?></a>
        <?php else: ?>
            <span class="disabled"><?= $this->last; ?></span>
        <?php endif; ?>
        &nbsp; Showing <?php echo $this->firstItemNumber, '-', $this->lastItemNumber, ' in ', $this->totalItemCount; ?>
    </div>
 </div>