<script type="text/javascript">
$(document).ready(function(){
  $('.rule-list-row').click(function(){
    var rule_id = $(this).attr('id');
    //$('#facade').css('height',$(document).height());
    $('#facade').css('display','block');
    if(rule_id == 'nomatch'){
        $.ajax({
            type: "GET",
            url: '/rule/add',
            success: function(data){
            	$('#rule-details-popup').empty();
    	        $('#rule-details-popup').html(data);
    	        $('#rule-details-popup').css('display', 'block');
    	        $('#facade').css('display','none');
    	        $('#name').focus();
            }
        });
    } else {
	    $.ajax({
	      url: '/rule/viewrule',
	      type: 'POST',
	      data: { rule_id:rule_id },
	      success: function(data){
	        $('#rule-details-popup').empty();
	        $('#rule-details-popup').html(data);
	        $('#rule-details-popup').css('display', 'block');
	        $('#facade').css('display','none');
	      }
	    });
    }
  });

  $('.delete-from-list').click(function(){
    var del_conf = confirm("Deleting Rule from table. Are you sure?");
	if(del_conf == 1){
    var aid = $(this).attr('id');
    console.log('Delete rule '+aid);
    $.ajax({
      url : '/rule/delete',
      type: 'POST',
      data: { aid:aid },
      success: function(data){
         if(isNaN(parseInt(data)))
             alert(data);
         else
        	 location.reload();
      }    
      });
	}
    return false;
  });
});
</script>

<ul class="phpip-list" id="rules-list">
<?php foreach($this->ruleslist as $rule): ?>
    <li class="rule-list-row" id="<?=$rule['rule_id']?>">
        
        <div class="col-task"><?=htmlentities($rule['task'])?></div>
        <div class="col-trigger"><?=htmlentities(@$rule['trigger_event_name'])?></div>
        <div class="col-category"><?=htmlentities(@$rule['category_name'])?></div>
        <div class="col-country"><?=htmlentities(@$rule['country_name'])?></div>
        <div class="col-origin"><?=htmlentities(@$rule['origin_name'])?></div>
        <div class="col-type"><?=htmlentities(@$rule['f_type'])?></div>
        <div class="col-notes"><?=htmlentities(@$rule['detail'])?></div>
        <div class="col-delete" >
                <span class="delete-from-list ui-icon ui-icon-trash" id="<?=$rule['rule_id']?>" style="float:right;" title="Delete rule"></span>
        </div>
    </li>
<?php endforeach; ?>
</ul>
