<?php
$cFront = Zend_Controller_Front::getInstance ();
$module = $cFront->getRequest ()->getModuleName ();
$module = strtolower ( $module );

$controller = $cFront->getRequest ()->getControllerName ();
$controller = strtolower ( $controller );

$action = $cFront->getRequest ()->getActionName ();
$action = strtolower ( $action );
$translate = Zend_Registry::get('ZT');
$header = '';
if ($module != 'default') {
	$header = "<a href=\"/$module\">".$this->translate->_($module)."</a>";
}

if ($controller != 'index') {
	if ($header != '') {
		$header .= " - ";
	}
	$header .= "<a href=\"/$module/$controller\">".$this->translate->_($controller)."</a>";
}

if ($header != '') {
	$header .= " - ";
}
$header .= ' <a href="">' . $action . '</a>';

if ($header != '') {
?>
<div id="inner-header" style="font-size: 1em;">
	<div id="inner-header-title"><?="$header"?></div>
<?php
	if ($module == 'default' && ($controller == 'index' || $controller == 'matter')) {
		?>
	<div id="inner-header-search">
		<input id="matter-search" type="text" name="matter_search" /> 
		<select style="width: 100px;" id="matter-option" name="search_field">
			<option value="Ref" selected><?=$translate->_("caseref")?></option>
			<option value="Responsible"><?=$translate->_("Responsible")?></option>
		</select> 
		<input id="matter-ref-search" type="button" name="search" value=<?=$translate->_("Quick Search")?> />
	</div>
<?php
	}
	if ($module == 'default' && $controller == 'matter' && $action == 'view') {
		?>
	<div id="matter-head-navigation">
		<button title="Previous" class="matter-navigation" 
			id="<?=($this->matter_index === "") ? ((int)$this->matter_index)-1 : "matter-previous-" . $this->matter_id ?>">
			<span class="ui-icon ui-icon-seek-prev"></span>
		</button>
		<button title="Next" class="matter-navigation" 
			id="<?=($this->matter_index === "") ? ((int)$this->matter_index)+1 : "matter-next-" . $this->matter_id ?>">
			<span class="ui-icon ui-icon-seek-next"></span>
		</button>
	</div>
<?php 
	} ?>
</div>
<?php 
}?>