<?php

#echo $this->doctype('HTML5'); ?>

<?= $this->doctype() ?>
<html>
<head>
<?= $this->headTitle() ?>
<?= $this->headMeta() ?>
<?= $this->headLink()
        ->appendStylesheet($this->baseUrl('/css/reset-all.css'), 'all')
        ->appendStylesheet($this->baseUrl('/css/layout-screen.css'), 'screen')
        ->appendStylesheet($this->baseUrl('/css/content-screen.css'), 'screen')
?>
<?= $this->headScript() ?>
</head>

<body<?= 0 != count($this->routeContext) ? ' class="' . implode(' ', array_unique($this->routeContext)) . '"' : '' ?>>
<div id="page">
    <h1><a href="<?= $this->url(array(), null, true) ?>">PRTouch</a></h1>
    <div id="content">
    <div id="content-body"><?= $this->layout()->content ?></div>


        <div id="header">
<? #$this->placeholder('header'); ?>
<?= $this->render('header.phtml') ?>

