<?php
#echo $this->doctype('HTML5');
echo $this->doctype(); ?>
<html>
<head>
<?= $this->headTitle() ?>
<?= $this->headMeta() ?>
<?= $this->headLink()
        ->appendStylesheet($this->baseUrl('/css/layout-screen-login.css'), 'screen')
?>
<?= $this->headScript() ?>
</head>

<body<?= 0 != count($this->routeContext) ? ' class="' . implode(' ', array_unique($this->routeContext)) . '"' : '' ?>>
<?php #$this->placeholder('header'); ?>
<?php #$this->render('header.phtml') ?>

<div id="page">
    <div id="logo"><a id="logo" href="<?= $this->url(array(), null, true) ?>">phpIP</a></div>
    <div id="content">
    <div id="content-body"><?= $this->layout()->content ?></div></div>
</div>
