<style type="text/css" >
#events-box{
  display:block;
}
#events-list{
  margin: 0px;
  padding: 0px;
  max-height:300px;
  overflow:auto;
}
.phpip-lists{
    margin:0px 5px 5px;
    padding: 4px;
    float:left;
    background: #B5D9E5;
    display:block;
    box-shadow: 2px 2px 1px #888888;
}
.phpip-list li{
    list-style: none;
    color: #3F3F38;
    border-bottom: 1px solid #DDD;
    background: #FFF;
}
.phpip-list li:hover {
    background: #C8E8F3;
}
.list-headers {
    background: #1E4262;
    color: #FFF;
    border: none;
    padding: 4px 6px;
}
.phpip-list li:last-child {
    border-radius: 0 0 4px 4px;
}
.col-code{
    display:inline-block;
    padding: 4px 0px 4px 6px;
    width: 130px;
}
.col-name{
    display:inline-block;
    width: 130px;
}
.col-notes{
    display:inline-block;
    width: 350px;
}
.col-delete{
    display:none;
    width: 40px;
    text-align: center;
}
.home-box{
  float:left;
}
#events-tab{
  background: #B5D9E5;
  display:block;
  width:40px;
  padding: 5px 5px 0px;
}
.event-list-row{
  cursor: pointer;
}
#event-details-popup{
  display: none;
  /*z-index: 101;
  position: absolute;*/
	width: 670px;
}
.filter-input{
  border: 1px inset #555;
  font-size: 9px;
  padding: 2px 1px;
  width: 50px;
}
/*#event-details-content{
	width: 99.5%;
}*/
#event-details-nav{
  text-align:center;
  display: none;
}
#event-details-nav img{
  margin-left: 10px;
  cursor: pointer;
}
.event-list-row:hover .col-delete{
	display: inline-block;
}
.event-navigation{
	margin-bottom: 5px;
}

</style>
<script type="text/javascript">
$(document).ready(function(){
  $('.event-list-row').click(function(){
		$('#event-details-popup').load('/event/view', { 'event_id': $(this).attr('id') }).show();
  });

  $('#filter-code').keyup(function(){
		$('#event-table-list').load('/event/filter/co/0/term/'+$(this).val());
  });

  $('#event_name').keyup(function(){
		$('#event-table-list').load('/event/filter/co/1/term/'+$(this).val());
  });

  $('.delete-from-list').click(function(){
	    var del_conf = confirm("Deleting event from table. The event will only be deleted if not used in other tables.");
		if(del_conf == 1){
	    	var aid = $(this).attr('id');
	    	$.ajax({
	      	url : '/event/delete',
	      	type: 'POST',
	      	data: { aid:aid },
	      	success: function(data){
	        	if(isNaN(parseInt(data)))
	          		alert(data); 
	        	else 
		        	location.reload();     
          	}
			});
		}
	    return false;
  });

  $( "button, input:button" ).button();

});
</script>
<div id="events-tab">Event names</div>
<div id="events-box" class="place-card">
<?php if(count($this->eventslist)): ?>
    <div class="list-headers">
    	<div class="col-code">Code <input type="text" size=20 name="filter-code" id="filter-code" class="filter-input" /></div>
        <div class="col-name">Name <input type="text" size=20 name="event_name" id="event_name" class="filter-input" /></div>
        <div class="col-notes">Notes</div>
    	<div class="col-delete" >Delete</div>
    </div>
<div id="event-table-list">
<ul class="phpip-list" id="events-list">
<?php foreach($this->eventslist as $event): ?>
    <li class="event-list-row" id="<?=$event['event_id']?>">
    	
    	<div class="col-code"><?=htmlentities($event['code'])?></div>
        <div class="col-name"><?=htmlentities($event['name'])?></div>
        <div class="col-notes"><?=htmlentities($event['notes'])?></div>
    	<div class="col-delete" >
    		<span class="delete-from-list ui-icon ui-icon-trash" id="<?=$event['event_id']?>" style="float:right;" title="Delete event"></span>
    	</div>
    </li>
<?php endforeach; ?>
</ul>
</div>
<?php   endif; ?>
</div>
<div id="event-details-popup" class="place-card" style="float: left"></div>
<div id="facade"></div>
