<style type="text/css">
select {
	width: 150px;
}

#edit-event-content {
	width: 98%;
	background: #FFF;
	display: block;
	border: 1px inset #888;
	padding: 5px;
}

#edit-event-content label {
	display: inline-block;
	text-align: left;
	width: 100px;
	margin: 0px 5px 5px 5px;
	vertical-align: top;
}

.event-input-wide {
	display: inline-block;
	width: 255px;
	border: 1px solid #FFF;
	background: #FFF;
	padding: 1px 2px;
	vertical-align: top;
	margin-bottom: 3px;
	min-height: 16px;
}

.event-input-narrow {
	display: inline-block;
	width: 125px;
	border: 1px solid #FFF;
	background: #FFF;
	padding: 1px 2px;
	vertical-align: top;
	margin-bottom: 3px;
	min-height: 16px;
}

.teditable {
	min-height: 32px;
}

.close-button {
	background: #f00;
	float: right;
	padding: 2px 4px 0px;
	cursor: pointer;
	font-family: arial;
}

#edit-event-head {
	display: block;
	width: 98%;
	background: #1E4262;
	color: #FFF;
	padding: 5px;
	border: 1px solid #1E4262;
}

.validation-errors {
	color: #F00;
	padding: 5px;
}

#valid-error {
	display: block;
	margin: 0px 0px 5px 10px;
}

.event-info-set {
	background: #EFEFEF;
	border: 1px inset #888;
}

input {
	border: 0px;
}

</style>
<script type="text/javascript">
$(document).ready(function(){
    $.editable.addInputType('autocomplete', {
		element: $.editable.types.text.element,
		plugin: function(settings, original){
			$('input', this).autocomplete(settings.autocomplete);
		}
    });

    $('.editable').editable('/event/update', {
                submitdata: function(value,settings){
                        var event_id = $('#event-id').val();
                        var field_name = $(this).attr('id');
                        return { event_id : event_id , field : field_name}
                },
                placeholder: '',
                select : true,
                indicator : '<span class="icon-busy" />',
                tooltip: 'Click to edit...',
                data: function(value, settings){
                        return $("<div/>").html(value).text();
                }
    });
    
    $('.teditable').editable('/event/update', {
                submitdata: function(value,settings){
                        var event_id = $('#event-id').val();
                        var field_name = $(this).attr('id');
                        return { event_id : event_id , field : field_name  }
                },
                type: 'textarea',
                placeholder: '',
                select : true,
                indicator : '<span class="icon-busy" />',
                tooltip: 'Click to edit...',
                submit: 'ok',
                cancel: 'cancel',
                data: function(value, settings){
                        var tval = value.replace(/(<br>)*/g, '');
                        return $("<div/>").html(tval).text();
                }
    });
    

    $('.responsible-editable').editable('/event/update', {
        type: 'autocomplete',
        autocomplete: {
                        minLength: 1,
                        source: "/actor/get-all-logins",
                        select: function( event, ui ) {
                        this.value = ui.item.value;  // assign category name back to the form element
                                fvalue = ui.item.id; // Responsible ID
                                dvalue = ui.item.value;
                        $(event.target.form).submit(); //submit the form
                        }
        },
        submitdata: function(value, settings){
                        var field_name = $(this).attr('id');
                        return { 
                                event_id: $('#event-id').val(), 
                                field: field_name,
                                value: fvalue,
                                dvalue: dvalue 
                        }
                },
                callback : function(value, settings) { // Reset variables after submission
                        fvalue = '';
                        dvalue = '';
                },
                id: 'field', // the object id is the form field name
                placeholder: '',
                indicator: '<span class="icon-busy" />',
                tooltip: 'Click to edit...',
                select: true
    });

    $('.delete-event').click(function(){
	    var del_conf = confirm("Deleting Event name from table. Are you sure?");
		if(del_conf == 1){
	    	var aid = $(this).attr('id');
	    	$.ajax({
	      		url: '/event/delete',
	      		type: 'POST',
	      		data: { aid:aid },
	      		success: function(data){
	        		if(isNaN(parseInt(data)))
	          			alert(data); 
	        		else 
		        		location.reload();     
          		}
			});
		}
	    return false;
	});

    $('input[name=status_event]').change(function(){
        $.post('/event/update', { event_id : $('#event-id').val(), field : 'status_event', value: $('input[name=status_event]:checked').val()});
    });


    $('input[name=is_task]').change(function(){
        $.post('/event/update', { event_id : $('#event-id').val(), field : 'is_task', value: $('input[name=is_task]:checked').val()});
    });

    $('input[name=unique]').change(function(){
        $.post('/event/update', { event_id : $('#event-id').val(), field : 'unique', value: $('input[name=unique]:checked').val()});
    });

    $('input[name=uqtrigger]').change(function(){
        $.post('/event/update', { event_id : $('#event-id').val(), field : 'uqtrigger', value: $('input[name=uqtrigger]:checked').val()});
    });

    $('input[name=use_matter_resp]').change(function(){
        $.post('/event/update', { event_id : $('#event-id').val(), field : 'use_matter_resp', value: $('input[name=use_matter_resp]:checked').val()});
    });

    $('input[name=killer]').change(function(){
        $.post('/event/update', { event_id : $('#event-id').val(), field : 'killer', value: $('input[name=killer]:checked').val()});
    });

    $('.close-button').click(function(){
        $('#event-details-popup').hide();
        $('#event-details-used-in').hide();
        $('#facade').hide();
    });
    
    $( "button, input:button" ).button();

});
</script>

<div id="edit-event-head">
	Event name information <span class="close-button">X</span>
</div>
<div id="edit-event-content">
	<input type="hidden" name="event_id" id="event-id"
		value="<?=$this->event['code']?>" />
	<fieldset class="event-info-set">
		<legend>Task event details - ID: <?=$this->event['code']?></legend>
                <label for="code" title="<?=$this->eventComments['code']?>"><b>Code</b></label>
                <span class="event-input-wide editable" id="code"><?=htmlentities($this->event['code'])?></span>
                <label for="is_task" title="<?=$this->eventComments['is_task']?>">Is task</label>
                <span class="event-input-narrow opt-editable" id="is_task">
                        <input type="radio" name="is_task" value="1" <?php echo ($this->event['is_task'])? 'checked="checked"' : ""; ?> />YES&nbsp;&nbsp;
                        <input type="radio" name="is_task" value="0" <?php echo ($this->event['is_task'])? '' :'checked="checked"'; ?> />NO
                </span>
                <label for="name" title="<?=$this->eventComments['name']?>">Name</label>
                <span class="event-input-wide editable" id="name"><?=$this->event['name']?></span>
                <label title="<?=$this->eventComments['status_event']?>">Is status event</label>
                <span class="event-input-narrow opt-editable" id="status_event">
                        <input type="radio" name="status_event" value="1" <?php echo ($this->event['status_event'])? 'checked="checked"' : ""; ?> />YES&nbsp;&nbsp;
                        <input type="radio" name="status_event" value="0" <?php echo ($this->event['status_event'])? '' :'checked="checked"'; ?> />NO
                </span>
                <label for="default_responsible" title="<?=$this->eventComments['default_responsible']?>">Default responsible</label>
                <span class="event-input-wide responsible-editable" id="default_responsible"><?=$this->event['default_responsible']?></span>
                <label for="unique" title="<?=$this->eventComments['unique']?>">Is unique</label> 
                <span class="event-input-narrow opt-editable" id="unique">
                        <input type="radio" name="unique" value="1" <?php echo ($this->event['unique'])? 'checked="checked"' : ""; ?> />YES&nbsp;&nbsp;
                        <input type="radio" name="unique" value="0" <?php echo ($this->event['unique'])? '' :'checked="checked"'; ?> />NO
                </span>
                <label for="use_matter_resp" title="<?=$this->eventComments['use_matter_resp']?>">Use matter responsible</label>
                <span class="event-input-wide opt-editable" id="use_matter_resp">
                        <input type="radio" name="use_matter_resp" value="1" <?php echo ($this->event['use_matter_resp'])? 'checked="checked"' : ""; ?> />YES&nbsp;&nbsp;
                        <input type="radio" name="use_matter_resp" value="0" <?php echo ($this->event['use_matter_resp'])? '' :'checked="checked"'; ?> />NO
                </span>
                <label for="uqtrigger" title="<?=$this->eventComments['uqtrigger']?>">Unique trigger</label>
                <span class="event-input-narrow opt-editable" id="uqtrigger">
                        <input type="radio" name="uqtrigger" value="1" <?php echo ($this->event['uqtrigger'])? 'checked="checked"' : ""; ?> />YES&nbsp;&nbsp;
                        <input type="radio" name="uqtrigger" value="0" <?php echo ($this->event['uqtrigger'])? '' :'checked="checked"'; ?> />NO
                </span>
                <label for="killer" title="<?=$this->eventComments['killer']?>">Is killer</label>
                <span class="event-input-wide opt-editable" id="killer">
                        <input type="radio" name="killer" value="1" <?php echo ($this->event['killer'])? 'checked="checked"' : ""; ?> />YES&nbsp;&nbsp;
                        <input type="radio" name="killer" value="0" <?php echo ($this->event['killer'])? '' :'checked="checked"'; ?> />NO
                </span><BR />
                <label for="notes" title="<?=$this->eventComments['notes']?>">Notes</label>
                <span class="event-input-wide teditable" id="notes"><?=htmlentities($this->event['notes'])?></span>
		<button title="Delete event" class="delete-event" id="<?=$this->event['code']?>" style="float: right; margin-top: 10px; margin-right: 16px;">
			<span class="ui-icon ui-icon-trash" style="float: left;"></span>
			Delete
		</button>
	</fieldset>

	<input type="hidden" value="" id="country-code" name="country-code" /> 
	
</div>
