<style type="text/css">
.list-row{
  border-bottom: 1px solid #ccc;
  width:187px;
  padding:4px;
  background: #FFF;
  -moz-border-radius: 0px 4px 4px 4px;
  -webkit-border-radius: 0px 4px 4px 4px;
}

.listrow-header{
  margin-bottom: 5px;
  cursor: pointer;
  padding:4px;
  background: #B5D9E5;
}
.col{ width: 83px; display: inline-block; vertical-align: top;}
.col-large{ width: 166px; }
.actor-list-row-1:hover{ cursor: pointer}

</style>
<link href="/js/css/smoothness/jquery-ui-1.8.17.custom.css" media="screen" rel="stylesheet" type="text/css" >
<script type="text/javascript" src="/js/jquery-ui-1.8.17.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.jeditable.js"></script>
<script type="text/javascript">

$(document).ready(function(){
  $('.actor-list-row-1').click(function(){

    var actor_id = $(this).attr('id');
    $('#facade').css('height',$(document).height()+200);
    $('#facade').css('display','block');
    $.ajax({
      url: '/matter/actor/',
      type: 'POST',
      data: { actor_id:actor_id },
      success: function(data){
        $('#actor-details-content').empty();
        $('#actor-details-content').html(data);
        ren_left = Math.round($(window).width()/2) - Math.round($('#actor-details-popup').width()/2);
        $('#actor-details-popup').css('left', ren_left);
        $('#actor-details-popup').css('top', '50px');
        $('#actor-details-popup').css('display', 'block');
      }
    });
  });



});
</script>

<div class="listrow" style="margin: 0 5px 1px;">
<span >Matter Dependencies</span>
<div class="list-row"  >
<div class="col">Ref</div>
<div class="col">Role</div>
</div>
<div  style="width: 210px; height: 200px; overflow: auto ">
<?php 
$type = '';
$close_type = 0;
$add_empty_row = 0;

foreach($this->matter_dependencies as $matter){
?>
<div class="list-row"  >
<div class="col"><a href="/matter/view/id/<?= $matter['id']?>" target="_blank"><?= $matter['UID']?></a></div>
<div class="col"><?= $matter['role']?></div>
</div>
<? } ?>
</div>
</div>

<div class="listrow" >
<span >Other Actor Dependencies</span>
<div class="list-row"  >
<div class="col">Actor</div>
<div class="col">Dependency</div>
</div>
<div  style="width: 210px; height: 200px; overflow: auto ">
<?php 
$type = '';
$close_type = 0;
$add_empty_row = 0;

foreach($this->other_actor_dependencies as $actor){
?>
<div class="list-row"  >
<div class="col actor-list-row actor-list-row-1" id="<?=$actor['id']?>"><? echo htmlentities($actor['Actor'])?></div>
<div class="col "><? echo htmlentities($actor['Dependency'])?></div>
</div>
<? } ?>
</div>
</div>

