<style type="text/css">
.status-row{
display:block;
}
.eventlist-col-name{
display:inline-block;
width: 150px;
vertical-align: top;
}
.eventlist-col-date{
display:inline-block;
width: 125px;
vertical-align: top;
}

.eventlist-col-number{
display:inline-block;
width: 80px;
vertical-align: top;
}

.eventlist-col-refer{
display:inline-block;
width: 200px;
vertical-align: top;
}

.eventlist-col-notes{
display:inline-block;
width: 320px;
vertical-align: top;
}



.eventlist-col{
display:inline-block;
width: 150px;
vertical-align: top;
}

#MatterAllEvent:hover{
    cursor: pointer;
}

#MatterAllEventBlock{
    width: 941px;
}

</style>

<script type="text/javascript">
    $("#MatterAllEvent").click(function(event){
        $('#event-pop-up').css('display','none');
    }); 
</script>  


<?php // Matter Open Tasks ?> 
<?php //if(isset($this->matter_open_tasks)):
//print_r($this->matter_open_tasks);
   $trigger_id = "";
   $add_empty_row = 0;
 ?>
<div id="MatterAllEventBlock" class="listrow" ><div id="MatterAllEvent" class="status-row">
<span class="eventlist-col-name" style="margin-left: 5px;">All Events</span>
<span class="eventlist-col-date" >Date</span>
<span class="eventlist-col-number" >Number</span>
<span class="eventlist-col-notes" >Notes</span>
<span class="eventlist-col-refer" >Refers to</span>
</div>
<div class="list-matter-block-info" style="max-height: 350px; min-height: 100px; width:98%; height: auto;" >
<?php foreach($this->matter_events as $matter_event): ?> 
<div class="status-row">
<span class="eventlist-col-name"><?=$matter_event['name']?></span>
<span class="eventlist-col-date" ><?=$matter_event['event_date']?></span>
<span class="eventlist-col-number" ><?=$matter_event['detail']?></span>
<span class="eventlist-col-notes" ><?=$matter_event['notes']?></span>
<span class="eventlist-col-refer" ><? if($matter_event['alt_matter_ID']){ ?>
    	<a href="/matter/view/id/<? echo $matter_event['alt_matter_ID']?>"><?=$matter_event['alt_caseref'] ?></a> <?=$matter_event['country'] . " " . $matter_event['origin'] . " " . $matter_event['matter_type'];
    } ?></span>
</div>
<? endforeach; ?>
</div>
</div>
<?php //endif; ?>

