<script type="text/javascript" src="/js/jquery-ui-1.8.17.custom.min.js"></script>
<link href="/js/css/smoothness/jquery-ui-1.8.17.custom.css" media="screen" rel="stylesheet" type="text/css" >


       
<style type="text/css">


#MatterAddActor:hover{
    cursor: pointer;
}

.formtitle{
    width:90px;
    display: inline-block;
    margin-bottom: 10px;
}

</style>

<script type="text/javascript">
$(document).ready(function(){
    var role_search = "<?=$this->role_search?>";    

    $('.role_search').click(function() { 
        
        role_search = $(this).val();
         $.ajax({
                type: "GET",
                url: "/matter/map-actor-role/id/<?=$this->matter_id?>/role/<?=$this->role?>/role_search/" + role_search ,
                success: function(data){
                    $('#mapactor-pop-up').html(data);
                }
        });
    } );

    $("#cancel").click(function(event){
        $('#mapactor-pop-up').css('display','none');
        $('#facade').css('display','none');
    }); 

    $("#MatterAddActor").click(function(event){
        $('#mapactor-pop-up').css('display','none');
        $('#facade').css('display','none');
    }); 
    $( "#actor" ).autocomplete({
            minLength: 1,
            source: "/matter/get-all-actors/role/" + role_search ,
            focus: function( event, ui ) {
                    /*$( "#actor" ).val( ui.item.id );*/
                    return false;
            },
            select: function( event, ui ) {
                    $( "#actor" ).val( ui.item.value );
                    $( "#actor-id" ).val( ui.item.id );
                    return false;
            }
    });
    
});
</script>  
<form>
<div class="listrow" style=""width:100%><div id="MatterAddActor" class="status-row">
<span class="eventlist-col-name" style="margin-left: 5px;">Add Actor</span>
</div>
<div class="list-matter-block-info" style="max-height: 350px; min-height: 100px; width:98%; height: auto;" >
<span class="formtitle">Search in Role:</span><input class="role_search" name="role_search" type="radio" value="<?=$this->role?>" <?
if($this->role_search == $this->role) 
	echo " checked='checked'";
?>>
<?=$this->role_name[0]['name']?>, <input class="role_search" name="role_search" type="radio" value="1" <?
if($this->role_search == 1) 
	echo " checked='checked'";
?>> All

<br>
<span class="formtitle">Add Actor:</span> <input id="actor" width="200"/>
        <input type="hidden" id="actor-id" style="width:200px"/>
<input id="submit" type="submit" value="Add">
<input id="cancel" type="button" value="Cancel">
</div>
</form>
<?php //endif; ?>

