<script type="text/javascript">
$(document).ready(function(){
    $('#national-matter-cancel').click(function(){
        $('#add-matter-popup').hide();
        $('#facade').hide();
    });

   $('#national-matter-submit').on('click', function(){
        var form_data = $('#add-matter-form').serializeArray();
        var invalid = false;
        $('.validation-errors').empty();
        if(invalid)
            $('.validation-errors').show();
        else{
            $('.validation-errors').hide();
            $.post('/matter/national', { fdata: form_data, matter_ID: $('#this-matter-id').val() }, function(data){
				if( data != '' ){
					$('#add-matter-popup').hide();
                    $('#facade').hide();
                    $(location).attr("href", '/matter/filter/Ref/' + $('#matter-caseref-id').val() + '/origin/' + $('#matter-origin-id').val());
				}else
					alert("Adding national phases failed");
            });
        }
   });
  
    $('#additional-country').autocomplete({
        minLength: 2,
        source: "/matter/get-country-codes",
        autoFocus: true,
        select: function( event, ui ) {
			var mindex = $('#national-phases > div').size();
			var new_country = '<div id="nmp-' + mindex + '">'
				+ '<input type="hidden" name="matter_country[' + mindex + ']" value=' + ui.item.id + ' />'
    			+ '<span class="national-countries">' + ui.item.value + '</span>'
				+ '<input type="text" name="entered_date[' + mindex + ']" class="entered-date" value="" id="' + mindex + '"/>'
				+ '<input type="hidden" name="alt_entered_date[' + mindex + ']" id="alt-entered-date-' + mindex + '" value="" />'
				+ '<span class="national-matter-remove ui-icon ui-icon-trash" id="' + mindex + '" title="Remove" style="float: left" onclick="$(\'#nmp-'+ mindex + '\').remove();"></span></div>';
			$('#national-phases').append(new_country);
			$('.entered-date').datepicker({
				showOn: 'focus',
				dateFormat: 'dd/mm/yy',
				altField: '#alt-entered-date' + mindex,
				altFormat: 'yy-mm-dd',
			})
		},
		close: function( event, ui ) {
			$("#additional-country").val('');
        }
    });

   $('.entered-date').datepicker({
        showOn: 'focus',
        dateFormat: 'dd/mm/yy',
        altField: '#alt-entered-date' + $(this).attr('id'),
        altFormat: 'yy-mm-dd',
   });

   $('.national-matter-remove').on("click", function(){
     $('#nmp-'+ $(this).attr('id')).remove();
   });
   
   $( "button, input:button").button();
});
</script>
<style type="text/css" >
#add-matter-head{
  display:block;
  width: 400px;
  background: #1E4262;
  color: #FFF;
  padding: 5px;
  border: 1px solid #1E4262;
  border-radius: 5px 5px 0px 0px;
}

#add-matter{
  width: 400px;
  background: #FFF;
  display: block;
  border: 1px inset #888;
  padding: 5px;
  border-radius: 0px 0px 5px 5px;
}

#child-matter-options {
  border-top: 1px solid #DDD;
  padding-top: 8px;
}

#child-matter-options span{
  display:inline-block;
  text-align: right;
  width: 150px;
}

#child-matter-options label{
  text-align: left;
  width: 150px;
}

#add-matter input[type="text"]{
  width: 140px;
  border-radius: 3px;
  border: 1px inset #888;
  padding: 3px 2px;
}

#add-matter-actions{
  margin: 10px 0px 0px 0px;
  margin-left:30px;
}

.validation-errors{
display:none;
border:1px solid #f00;
color:#f00;
padding:5px;
width: auto;
margin-bottom: 10px;
  border-radius: 5px;
}

.validation-errors span{
    display: block;
    width: auto;
    margin-left: 20px;
}

.display-field{
  display: inline-block;
  width: 140px;
  border-radius: 3px;
  border: 1px solid #888;
  padding: 1px 2px;
  vertical-align: top;
  margin-bottom: 2px;
  min-height: 14px;
}

.national-countries{
  display: inline-block;
  width: 250px !important;
}
.entered-date{
  width: 100px !important;
}
.national-matter-remove{
  margin-left: 15px;
  cursor: pointer;
}
</style>

<div class="place-card">
<div id="add-matter-head">
Enter national phase <?=$this->caseref ?> <?=$this->country_code ?>
</div>
<div id="add-matter">
<div class="validation-errors">

</div>
<form type="post" id="add-matter-form" accept-charset="utf-8">

<input type="hidden" name="matter-caseref-id" id="matter-caseref-id" value="<?=$this->caseref?>" />
<input type="hidden" name="matter-category-code" id="matter-category-code" value="<?=$this->category_code?>" />
<input type="hidden" name="matter-origin-id" id="matter-origin-id" value="<?=$this->country_code?>" />

<label style="font-weight: bold; margin-left: 30px; width: 250px; text-align: left; display: inline-block">Country</label>
<label style="font-weight: bold; text-align: center; width: 100px; display: inline-block">Entered date</label>
<div id="national-phases" style="display:block;">
<?php 
$i=0;
foreach($this->country_options as $cflag){ ?>
<div id="nmp-<?=$i?>" >
	<input type="hidden" name="matter_country[<?=$i?>]" value="<?=$cflag['iso']?>" />
	<span class="national-countries"><?=$cflag['name']?></span>
	<input type="text" name="entered_date[<?=$i?>]" class="entered-date" value="" id="<?=$i?>"/>
	<input type="hidden" name="alt_entered_date[<?=$i?>]" id="alt-entered-date-<?=$i?>" value="" />
	<span class="national-matter-remove ui-icon ui-icon-trash" id="<?=$i?>" title="Remove" style="float: left;"></span>
</div>
<?php $i++; } ?>
</div>

<div id="nmp-add" >
	<span class="ui-icon ui-icon-plusthick" title="Add" style="float: left; margin-left: 15px"></span>
	<label for="additional-country" />
	<input id="additional-country" value="" style="width: 150px; float: left;" />
</div>

<div id="add-matter-actions">
	<input type="button" name="national-matter-cancel" id="national-matter-cancel" value="Cancel" style="float:right; margin-left: 4px;" />
	<input type="button" name="national-matter-submit" id="national-matter-submit" value="Submit" style="float:right;" />
</div>
</form>
</div>
</div>
