<style type="text/css">
#edit-matter-details h3 {
	border: 1px solid #4A7EBB;
	background: #93CDDD;
	color: #000;
	padding: 10px;
	text-align: center;
	margin: 20px 40px;
}

#edit-matter-table {
	margin-left: 20px;
}

#edit-matter-table th {
	text-align: right;
}

#edit-matter-table td {
	text-align: left;
	height: 10px;
}

.head-tab {
	color: #FFFFFF;
	background-color: #1E4262;
	padding: 5px 10px;
	margin-bottom: 10px;
	width: 100%;
}

.row-tab {
	border: 1px solid #888;
	background-color: #FFFFFF;
	padding: 5px 10px;
	margin-top: 5px;
	vertical-align: top;
}

.row-tab:hover {
	background-color: #AFB5C4;
	cursor: pointer;
}

.head-tab div {
	display: inline-block;
	text-align: center;
}

.row-tab div {
	display: inline-block;
	vertical-align: top;
	/*  text-align: left; */
}

/* added for display*/
.matter-title {
	vertical-align: top;
	text-align: left !important;
	margin: 5px;
	width: 180px;
}

#parent-matter {
	color: #999 !important;
	float: left;
}

#container-matter {
	color: #BBB !important;
	float: left;
}

.matter-name {
	text-align: left !important;
	margin: 5px;
	width: 720px;
	min-height: 90px;
}

.actor-block {
	display: inline-block;
	width: 170px;
	margin: 0px 10px 10px 0px;
	vertical-align: top;
	overflow-x: hidden;
	white-space: nowrap;
	mask-image: linear-gradient(left, black 90%, transparent);
	/*box-shadow: inset -5px -2px 10px #888888;*/
}

.row-head {
	background: none repeat scroll 0 0 #1E4262;
	color: wheat;
	text-align: center;
	width: 6%;
}

.list-matter-block {
	vertical-align: top;
	height: 23px;
	padding-left: 6px;
}

.list-matter-block-info {
	display: inline-block;
	vertical-align: top;
	background-color: #FFFFFF;
	border: 1px solid #DDD;
	border-style: inset;
	height: 100px;
	padding-left: 4px;
	overflow: auto;
	width: 100%;
}

.status-row {
	display: block;
	padding-left: 6px;
}

.status-col-name {
	display: inline-block;
	width: 150px;
	vertical-align: top;
}

.status-col-date {
	display: inline-block;
	width: 125px;
	vertical-align: top;
}

.status-col-number {
	display: inline-block;
	width: 125px;
	vertical-align: top;
}

.status-col {
	display: inline-block;
	width: 150px;
	vertical-align: top;
}

.task-col-name {
	display: inline-block;
	width: 300px;
	vertical-align: top;
}

.renewal-col-name {
	display: inline-block;
	width: 80px;
	vertical-align: top;
}

.renewal-col-number {
	display: inline-block;
	width: 20px;
	vertical-align: top;
}

.renewal-col-date {
	display: inline-block;
	width: 80px;
	vertical-align: top;
}

.classifier-name {
	display: inline-block;
	width: 100px;
	vertical-align: top;
}

.classifier-value {
	display: inline-block;
	vertical-align: top;
	max-width: 250px;
}

.classifier-main-name {
	display: inline-block;
	width: 80px;
	vertical-align: top;
	text-align: right;
	margin-bottom: 4px;
}

.classifier-main-value {
	padding-left: 10px;
	display: inline-block;
	width: 450px;
	vertical-align: top;
	text-align: left;
}

#MatterStatus:hover, #MatterStatusPop:hover, #MatterOpenTasks:hover,
	#MatterRenTasks:hover, #MatterClassifier:hover {
	cursor: pointer;
}

#mapactor-pop-up, #tasklist-pop-up, #event-pop-up, #classifier-popup {
	display: none;
	position: absolute;
	background: transparent;
	z-index: 1;
	box-shadow: 3px;
}

#mapactor-pop-up {
	position: fixed;
	margin: auto;
}

.help_cursor:hover {
	cursor: help;
}

.add-actor:hover {
	cursor: pointer;
}

.matter-role {
	font-weight: bold;
	color: #733e0f;
	display: inline-block;
	cursor: pointer;
}

.title-button {
	background: #C8E8F3;
	color: #000;
	text-shadow: 0 1px 0 #FFFFFF;
	padding: 2px 16px;
}

#matter-main-titles {
	border: 1px inset #000;
}

#title-action-div {
	float: right;
}

#title-action-div a {
	display: inline-block;
}

#title-action-div button {
	display: block !important;
	margin-bottom: 4px !important;
	width: 150px !important;
}

#responsible-actor-span {
	margin-left: 300px;
}

#add-classifier-popup, #add-matter-popup {
	display: none;
	z-index: 1;
	position: fixed;
	width: auto;
}

.title-editable {
	display: inline-block;
}

.matter-dead {
	color: #777 !important;
	text-decoration: line-through;
}

.actor-inherit {
	font-style: italic;
}

.actor-warn {
	color: red;
}

.matter-actor {
	cursor: pointer;
	overflow: hidden;
	text-overflow: ellipsis;
}

#actor-details-popup {
	display: none;
	z-index: 1;
	position: absolute;
	width: 670px;
}

#actor-details-nav {
	text-align: center;
}

#actor-details-nav img {
	margin-left: 10px;
	cursor: pointer;
}

#delete-actor {
	float: right;
	margin-top: 4px;
}

.required-field {
	font-weight: bold;
	margin-right: 4px;
}
</style>

<script type="text/javascript">
$(document).ready(function(){

        $("#MatterStatus").click(function(){
        	$('.ui-widget-overlay').show();
            $('#event-pop-up').load("/matter/eventlist/id/<?=$this->matter_record[0]['ID']?>")
            .css($(this).offset()).show().draggable();
        }); 

        $("#MatterOpenTasks").click(function(){
        	$('.ui-widget-overlay').show();
        	$('#tasklist-pop-up').load("/matter/tasklist/matter_id/<?=$this->matter_record[0]['ID']?>")
        	.css('top', $(this).offset().top).show().draggable();
        });

        $("#MatterRenTasks").click(function(){
        	$('.ui-widget-overlay').show();
            trig_id = <?=(isset($this->matter_open_tasks_ren[0]) ? $this->matter_open_tasks_ren[0]['trigger_ID'] : 0) ?>;
            if(trig_id == 0) return false;
         	$('#tasklist-pop-up').load("/matter/tasklist/event_id/" + trig_id, { renewal: 1 })
         	.css('top', $(this).offset().top).show().draggable();
        }); 

        $("#MatterClassifier").click(function(){
        	$('.ui-widget-overlay').show();
            $('#classifier-popup').load("/matter/classifierlist/id/<?=$this->matter_record[0]['ID']?>")
            .css('top', $(this).offset().top).show().draggable();
        });
 
        $(".add-actor").click(function(){
            role = $(this).attr('id').split('-');
            $('.ui-widget-overlay').show();
            //$('#facade').show();
            $('#mapactor-pop-up').load("/matter/map-actor-role/id/<?=$this->matter_record[0]['ID']?>/role/" + role[2])
            .css({top: $(this).offset().top, right: 150})
            .show().draggable();
        });

        $(".matter-role").click(function(){
            matter_role_id = $(this).attr('id').split('-');
            container_id = matter_role_id[2];
            role_id = matter_role_id[3];
            //$('.ui-widget-overlay').show();
            $('#facade').show();
            $('#mapactor-pop-up').load("/matter/role-actors/", { 
            	matter_id: $('input[name=matterId]').val(), 
            	container_id: container_id, 
            	role_id: role_id 
            }).css({width: 840, top: $(this).offset().top})
            .show().draggable();
        });

        $('#add-classifier-link').click(function(){
            //$('.ui-widget-overlay').show();
            $('#facade').show();
            $('#add-classifier-popup').load("/matter/add-title/cat_code/"+$(this).attr('data-code'))
            .css($(this).offset())
            .show().draggable();
        });

        $('#clone-matter-link').click(function(){
			//$('.ui-widget-overlay').show();
			$('#facade').show();
			$.get('/matter/clone', { 
            	category_id: $(this).attr('data-code'), 
            	country: $(this).attr('data-country'), 
            	origin: $(this).attr('data-origin'), 
            	type: $(this).attr('data-type') 
            },
            function(data){
            	$('#add-matter-popup').html(data).show().css({left: 400, top: 150}).draggable();
            });
        });
                  
        $('#child-matter-link').click(function(){
			//$('.ui-widget-overlay').show();
			$('#facade').show();
			$.get('/matter/child', { 
            	caseref: $(this).attr('data-caseref'), 
            	category_id : $(this).attr('data-code'), 
            	country: $(this).attr('data-country'), 
            	origin: $(this).attr('data-origin'), 
            	type: $(this).attr('data-type') 
            },
            function(data){
            	$('#add-matter-popup').html(data).show().css({left: 400, top: 150}).draggable();
            });
        });

        $('#national-matter-link').click(function(){
			//$('.ui-widget-overlay').show();
			$('#facade').show();
			$.get('/matter/national', { 
            	caseref: $(this).attr('data-caseref'), 
            	category_id: $(this).attr('data-code'), 
            	country: $(this).attr('data-country') 
            },
            function(data){
            	$('#add-matter-popup').html(data).show().css({left: 400, top: 150}).draggable();
            });
        });

        $('.title-editable').editable('/matter/edit-classifier', {
            type: 'textarea',
            submitdata: function(value,settings){
              var cid = $(this).attr('id');
              return { cid : cid };
            },
            select: true,
            submit: 'OK',
            cancel: 'X',
            indicator: '<span class="icon-busy" />',
            placeholder: '',
            tooltip: 'Click to edit...',
        });

        $('#matter-notes').editable('/matter/update-matter', {
            type: 'textarea',
            submitdata: function(value,settings){
              return { matter_id: $('#this-matter-id').val(), field: 'notes' };
            },
            submit: 'OK',
            cancel: 'X',
            select: true,
            indicator : '<span class="icon-busy" />',
            placeholder: '...',
            tooltip: 'Click to edit...',
            data: function(value, settings){
               return value.replace(/(<br>)*/g, '');
            }
        });

    $('#current-matter-edit').click(function(event){
      //$('.ui-widget-overlay').show();
      	$('#facade').show();
      	$('#add-matter-popup').load("/matter/edit/mid/"+$('#this-matter-id').val())
      		.show()
      		.css($(this).offset());
    });

    $('#add-classifier-link').hide();
    $('#matter-main-titles').mouseover(function(){
        $('#add-classifier-link').show();
    }).mouseout(function(){
        $('#add-classifier-link').hide();
    });

    $('.matter-actor').click(function(event){
      //$('.ui-widget-overlay').show();
      	$('#facade').show();
      	$('#actor-details-popup').load("/actor/view", { actor_id: this.id }, function(){ 
      		$(this).position({of: event, collision: "fit"}); 
      	}).show().draggable();
    });
                  
    $( "button, input:submit, input:button").button();
});
</script>

<div class="ui-widget-overlay" style="display: none"></div>
<div class="head-tab">
<?php
if ($this->matter_record [0] ['dead'])
	$matter_dead = "matter-dead";
else
	$matter_dead = "";
?>
	<div class="matter-title">
		<?=$this->matter_record[0]['category']?>
		<br/>
    	<span style="color: white; font-size: 16px; margin-right: 5px;" class="<?=$matter_dead?>">
    		<a href="/matter/filter/Ref/<?=$this->matter_record[0]['caseref']?>" style="color: white;" title="See family">
    			<?=$this->matter_record[0]['UID']?>
    		</a>
    		<button id="current-matter-edit" title="Advanced edit" style="background: transparent; border: transparent;">
				<span class="ui-icon ui-icon-wrench"></span>
			</button>
		</span>
<?php if ($this->matter_parent) {?>
		<br/>
		<a id="parent-matter" href="/matter/view/id/<?=$this->matter_parent [0] ['ID']?>" title="See parent">
			<?=$this->matter_parent [0] ['UID']?> (<?=$this->matter_parent [0] ['category_code']?>)
		</a>
<?php };
if ($this->matter_container) { ?>
		<br/>
		<a id="container-matter" href="/matter/view/id/<?=$this->matter_container [0] ['ID']?>" title="See container">
			<?=$this->matter_container [0] ['UID']?> (<?=$this->matter_container [0] ['category_code']?>)
		</a>
<?php }; ?>
	</div>
	<div class="matter-name">
		<div id="title-action-div">
			<button id="clone-matter-link"
				data-country="<?=$this->matter_record[0]['country_name']?>-<?=$this->matter_record[0]['country']?>"
				data-origin="<?=$this->matter_record[0]['origin']?>"
				data-type="<?=$this->matter_record[0]['type_code']?>"
				data-code="<?=$this->matter_record[0]['category']?>-<?=$this->matter_record[0]['category_code']?>">
				<span class="ui-icon ui-icon-copy" style="float: left;"></span>
				Clone matter
			</button>
			<button id="child-matter-link"
				data-caseref="<?=$this->matter_record[0]['caseref']?>"
				data-country="<?=$this->matter_record[0]['country_name']?>-<?=$this->matter_record[0]['country']?>"
				data-origin="<?=$this->matter_record[0]['origin']?>"
				data-type="<?=$this->matter_record[0]['type_code']?>"
				data-code="<?=$this->matter_record[0]['category']?>-<?=$this->matter_record[0]['category_code']?>">
				<span class="ui-icon ui-icon-link" style="float: left;"></span> 
				New child
			</button>
<?php if($this->national_phase){ ?>
			<button id="national-matter-link"
				data-caseref="<?=$this->matter_record[0]['caseref']?>"
				data-country="<?=$this->matter_record[0]['country_name']?>-<?=$this->matter_record[0]['country']?>"
				data-origin="<?=$this->matter_record[0]['origin']?>"
				data-type="<?=$this->matter_record[0]['type_code']?>"
				data-code="<?=$this->matter_record[0]['category']?>-<?=$this->matter_record[0]['category_code']?>">
				<span class="ui-icon ui-icon-flag" style="float: left;"></span>
				Enter nat. phase
			</button>
<?php } ?>
		</div>
<?php 
// Title box ("main" classifiers)
foreach ( $this->matter_classifier_main as $classifier ) :
	$cid = $classifier ['ID'];
	if ($classifier ['c_value']) {
		$classifier_arr [$classifier ['type']] = isset ( $classifier_arr [$classifier ['type']] ) ? $classifier_arr [$classifier ['type']] . ' ; <span class="title-editable" id="' . $cid . '" >' . htmlentities ( $classifier ['c_value'] ) . '</span>' : '<span class="title-editable" id="' . $cid . '" >' . htmlentities ( $classifier ['c_value'] ) . '</span>';
	}
	if ($classifier ['cv_value'])
		$classifier_arr [$classifier ['cv_type']] = isset ( $classifier_arr [$classifier ['cv_type']] ) ? $classifier_arr [$classifier ['cv_type']] . ' ; <span class="title-editable" >' . htmlentities ( $classifier ['cv_value'] ) . '</span>' : '<span class="title-editable" >' . htmlentities ( $classifier ['cv_value'] ) . '</span>';
	if ($classifier ['lnk_matter_id']) {
		$classifier_arr [$classifier ['type']] = "<a href='/matter/view/id/" . $classifier ['lnk_matter_id'] . "'>" . $classifier ['caseref'] . "</a> " . $classifier ['country'] . " " . $classifier ['origin'] . " " . $classifier ['matter_type'];
	}
endforeach;
if ($this->matter_classifier_container_main) :
	foreach ( $this->matter_classifier_container_main as $classifier ) :
		$cid = $classifier ['ID'];
		if ($classifier ['c_value']) {
			$classifier_arr [$classifier ['type']] = (isset ( $classifier_arr [$classifier ['type']] ) && $classifier_arr [$classifier ['type']]) ? $classifier_arr [$classifier ['type']] . ' ; <span class="title-editable" id="' . $cid . '" >' . htmlentities ( $classifier ['c_value'] ) . '</span>' : '<span class="title-editable" id="' . $cid . '" >' . htmlentities ( $classifier ['c_value'] ) . '</span>';
		}
		if ($classifier ['cv_value']) {
			$classifier_arr [$classifier ['cv_type']] = isset ( $classifier_arr [$classifier ['cv_type']] ) ? $classifier_arr [$classifier ['cv_type']] . ' ; <span class="title-editable" >' . htmlentities ( $classifier ['cv_value'] ) . '</span>' : '<span class="title-editable" >' . htmlentities ( $classifier ['cv_value'] ) . '</span>';
		}
		if ($classifier ['lnk_matter_id']) {
			$classifier_arr [$classifier ['type']] = "<a href='/matter/view/id/" . $classifier ['lnk_matter_id'] . "'>" . $classifier ['caseref'] . "</a> " . $classifier ['country'] . " " . $classifier ['origin'] . " " . $classifier ['matter_type'];
		}
	endforeach;
endif; ?>
		<div id="matter-main-titles">
<?php
if (count ( @$classifier_arr )) {
	foreach ( $classifier_arr as $type => $value ) : ?>
			<div class="" style="margin: 5px 0px; display: block; text-align: left;">
				<span class="classifier-main-name"><b><?=$type?></b></span>:
				<span class="classifier-main-value"><?=$value?></span>
			</div>
<?php
	endforeach	;
} else
	echo "...Hover the mouse here to add a title item...";
?>
			<button id="add-classifier-link" data-code="<?=$this->matter_record[0]['category_code']?>" style="position: absolute; width: 120px; margin-left: 50px; margin-top: -10px">
				<span class="ui-icon ui-icon-plusthick" style="float: left;"></span>
				Add title item
			</button>
		</div>
	</div>
</div>

<div class="listrow" style="width: 980px;">
	<div class="headlistrow">
		Actors
		<span id="responsible-actor-span">
			Responsible: <?=$this->matter_record[0]['responsible']?>
		</span>
		<button style="float: right; margin-top: -1px;" id="new-actor-0" class="add-actor">
			Add Actor
		</button>
	</div>
	<div class="list-matter-block-info" style="height: 150px;">
		<input type="hidden" 
			name="matterId" 
			id="this-matter-id"
			value="<?=$this->matter_id?>" /> 
		<input type="hidden"
			name="containerId" 
			id="this-container-id"
			value="<?=$this->matter_record[0]['container_ID']?>" />
<?php
if (!empty ( $this->matter_actors )) : 
// Actors box
	// Group actors in an array per role
	foreach  ( $this->matter_actors as $actor ) {
		$actors_per_role[$actor ['role_name']][] = $actor;
	}
	foreach ($actors_per_role as $role_name => $actors): ?>
		<div class="actor-block">
			<span class="matter-role" id="matter-role-<?=$this->matter_id?>-<?=$actors [0]['role']?>">
				<?=$role_name?>
				
			</span>
			<span class="add-actor ui-icon ui-icon-plusthick" id="add-actor-<?=$actors [0]['role']?>" title="Add Actor" style="display: inline-block"></span>
<?php 	
		foreach ( $actors as $actor ):
			$tooltip = '';
			$actor_display_name = ($actor ['display_name'] == "") ? $actor ['name'] . (($actor ['first_name']) ? (", " . $actor ['first_name']) : "") : $actor ['display_name'];			
			if ($actor ['actor_ref'])
				$actor_display_name .= " (" . $actor ['actor_ref'] . ")";			
				$tooltip = $actor ['actor_ref'];			
			if ($actor ['company_name'])
				$tooltip = $actor ['company_name'];			
			if ($tooltip):?>
			<div id="<?=$actor ['actor_ID']?>" class="matter-actor help_cursor <?=($actor ['inherited'] ? ' actor-inherit' : '')?><?=$actor ['warn'] ? ' actor-warn' : ''?>" title="<?=htmlentities ( $tooltip )?>">
				<?=$actor_display_name?>
				
			</div>
			<?php else:?>
			<div id="<?=$actor ['actor_ID']?>" class="matter-actor <?=$actor ['inherited'] ? ' actor-inherit' : ''?><?=$actor ['warn'] ? ' actor-warn' : ''?>">
				<?=$actor_display_name?>
				
			</div>
			<?php endif;
		endforeach;?>
		</div>
<?php 
	endforeach;
endif;?>
	</div>
</div>

<!-- Status box (main events) -->

<div class="listrow" style="width: 485px;">
	<div class="headlistrow" id="MatterStatus" style="margin-left: 3px;" title="Click for more detail">
		<span class="status-col-name">Status</span>
		<span class="status-col-date">Date</span> 
		<span class="status-col-number">Number</span>
		<span style="float: right;" class="ui-icon ui-icon-newwin"></span>
	</div>
	<div class="list-matter-block-info">
<?php
foreach ( $this->matter_events as $event ) :
	if ($this->matter_record [0] ['origin'] == 'EP')
		$CC = 'EP';
	else
		$CC = $this->matter_record [0] ['country'];
	$country_code = $this->matter_record [0] ['country'];
	$category = $this->matter_record [0] ['category_code'];
	$removethese = array (
			"/^$country_code/",
			'/ /',
			'/,/',
			'/-/',
			'/\//',
			'/\.[0-9]/' 
	);
	$cleanednumber = preg_replace ( $removethese, '', $event ['detail'] );
	$href = '';
	if ($event ['alt_matter_ID'] != "")
		$href = '/matter/view/id/' . $event ['alt_matter_ID'];
	else if (($event ['code'] == 'PUB' || $event ['code'] == 'GRT') && $category == 'PAT') {
		// Fix US pub number for Espacenet by keeping the last 6 digits after the year
		if ($CC == 'US' && $event ['code'] == 'PUB')
			$cleanednumber = substr ( $cleanednumber, 0, 4 ) . substr ( $cleanednumber, - 6 );
		$href = 'http://worldwide.espacenet.com/publicationDetails/biblio?DB=EPODOC&CC=' . $CC . '&NR=' . $cleanednumber;
	} else if ($event ['code'] == 'FIL') {
		if ($pubno = $this->matter_events [array_search ( 'PUB', array_column ($this->matter_events, 'code') )]['detail'] )
			$pubno = preg_replace ( $removethese, '', $pubno );
		switch ( $country_code ) {
			case 'EP':
				$href = 'https://register.epo.org/espacenet/application?number=EP' . $cleanednumber;
				break;
			case 'FR':
				if ( $category == 'PAT' && $pubno )
					$href = 'http://bases-brevets.inpi.fr/fr/document/' . $CC . $pubno . '.html';
				else if ( $category == 'TM' ) {
					if (substr ($event ['event_date'], -4 ) >= '2000')
						$cleanednumber = substr ( $cleanednumber, - 7 );
					$href = 'http://bases-marques.inpi.fr/Typo3_INPI_Marques/marques_resultats_liste.html?baseFr=on&baseCommu=on&baseInter=on&rechercher=Rechercher&recherche=recherche&numero=' . $cleanednumber;
				}
				break;
			case 'US':
				$year = substr ($event ['event_date'], -4 );
				$href = 'https://register.epo.org/ipfwretrieve?apn=US.' . $year . $cleanednumber . '.A';
				break;
			case 'GB':
				$href = 'http://www.ipo.gov.uk/p-ipsum/Case/ApplicationNumber/' . $CC . $cleanednumber;
				break;
			case 'EM':
				$href = 'https://oami.europa.eu/eSearch/#details/trademarks/' . $cleanednumber;
				break;
		}
	}
?> 
		<div class="status-row">
			<span class="status-col-name">
				<?=$event['name']?>
			</span> 
			<span class="status-col-date">
				<?=$event['event_date']?>
			</span> 
			<span class="status-col-number">
				<?php if($href !=  ""){ ?>
					<a href="<?=$href?>" target="_blank"><?=$event['detail']?></a>
				<?php } else {
					echo $event['detail'];
				}?>
			</span>
		</div>
<?php
endforeach;
?>
	</div>
</div>

<!-- Matter Open Tasks -->

<div class="listrow" style="width: 484px;">
	<div class="headlistrow" id="MatterOpenTasks" style="margin-left: 3px;" title="Click for more detail">
		<span class="task-col-name">
			Open tasks
		</span>
		<span class="status-col-date">
			Due
		</span> 
		<span style="float: right;" class="ui-icon ui-icon-newwin"></span>
	</div>
	<div class="list-matter-block-info">
<?php
$trigger_id = "";
foreach ( $this->matter_open_tasks as $open_task ) :
	// Display the trigger event in the first iteration
	if ($trigger_id != $open_task ['trigger_ID']) {
		$trigger_id = $open_task ['trigger_ID'];
?>
		<div class="status-row" style="border-bottom: 1px solid #DDD; margin-top: 2px;">
			<span class="task-col-name">
				<b><?=$open_task['trigger_name'] ." - ". $open_task['trigger_detail'] ?></b>
			</span>
			<span class="status-col-date"></span>
		</div>
<?php
	}
	if ($trigger_id == $open_task ['trigger_ID']) {
?> 
		<div class="status-row">
			<span class="task-col-name help_cursor" title="<?=htmlentities($open_task['notes']) ?>">
<?php
		echo $open_task['task_name'];
		if ($open_task ['detail'] != "")
			echo ": " . $open_task ['detail'];
?>
			</span> 
			<span class="status-col-date">
				<?=$open_task['due_date']?>
			</span>
		</div>
<?php
	}
endforeach;
?>
	</div>
</div>


<!-- Matter Open Renewals -->

<div class="listrow" style="width: 240px;">
	<div class="headlistrow" id="MatterRenTasks" title="Click for more detail">
		<span class="renewal-col-name">
			Renewals</span> 
		<span class="renewal-col-date">
			Due</span> 
		<span style="float: right;" class="ui-icon ui-icon-newwin"></span>
	</div>
	<div class="list-matter-block-info">
<?php
$ren_trigger_id = "";
foreach ( $this->matter_open_tasks_ren as $open_task_ren ) :
	// Display the trigger event in the first iteration
	if ($ren_trigger_id != $open_task_ren ['trigger_ID']) {
		$ren_trigger_id = $open_task_ren ['trigger_ID'];
?>
		<div class="status-row"
			style="margin: 5px 0px; border-bottom: 1px solid #DDD;">
			<span class="renewal-col-name">
				From: <b><?=$open_task_ren['trigger_name']?></b>
			</span>
			<span class="renewal-col-date"></span> 
			<span class="renewal-col-number"></span>
		</div>
<?php
	}
	if ($ren_trigger_id == $open_task_ren ['trigger_ID']) {
?> 
		<div class="status-row">
			<span class="renewal-col-name">
				<?=$open_task_ren['detail']?>
			</span> 
			<span class="renewal-col-date">
				<?=$open_task_ren['due_date']?>
			</span>
		</div>
<?php
	}
endforeach;
?>
		<div class="status-row">&nbsp;</div>
<?php
if (isset ( $this->matter_expiry ['expire_date'] )) :
	echo "Expiry: " . $this->matter_expiry ['expire_date'];
	echo ($this->matter_expiry ['term_adjust'] > 0) ? "<br>(PTA: " . $this->matter_expiry ['term_adjust'] . " days)" : "";
endif;
?>
	</div>
</div>

<!-- Classifiers -->

<?php 
$trigger_id = "";
?>
<div class="listrow" style="width: 370px;">
	<div class="headlistrow" id="MatterClassifier" title="Click for more detail">
		<span class="status-col-name">
			Classifier
		</span>
		<span style="float: right;" class="ui-icon ui-icon-newwin"></span>
	</div>
	<div class="list-matter-block-info">

<?php
$ctype = "";
$close_type = 0;
$count = 0;
foreach ( $this->classifiers as $classifier ) {
	if ($ctype != $classifier ['type']) {
		$ctype = $classifier ['type'];
		if ($close_type) {
?>
	</div>
<?php
			$count = 0;
		}
?>
	<div class="status-row" style="margin: 5px 0px;">
		<span class="classifier-name">
			<b><?=$classifier['type']?></b>
		</span>
<?php
		$close_type = 1;
	}
	if ($ctype == $classifier ['type']) {
		if ($count > 0)
			echo "&nbsp;|&nbsp;";
		$count ++;
		$show_title = 0;
		$classifier_value = substr ( $classifier ['value'], 0, 80 );
		if (strlen ( $classifier ['value'] ) > 80) {
			$classifier_value .= ' ...';
			$show_title = 1;
		}
?>
		<span class="classifier-value" title="<?php echo ($show_title)?$classifier['value']:'';?>">
<?php
		if ($classifier ['url'] == '')
			echo $classifier_value;
		else
			echo '<a href="' . $classifier ['url'] . '" target="_blank">' . $classifier_value . '</a>';
?>
		</span>
<?php
	}
}
if ($close_type)
	echo "</div>";
?>

	</div>
</div>

<!-- Notes -->

<div class="listrow" style="width: 350px;">
	<div class="headlistrow">
		<span class="status-col-name">Notes</span>
	</div>
	<div class="list-matter-block-info">
		<div class="status-row" style="margin: 5px 5px; min-height: 55px;" id="matter-notes">
			<?=nl2br(htmlentities($this->matter_record[0]['notes']))?>
		</div>
	</div>
</div>

<div id="event-pop-up"></div>
<div id="tasklist-pop-up"></div>
<div id="classifier-popup"></div>
<div id="mapactor-pop-up"></div>
<div id="add-classifier-popup">
	<input type="hidden" value="<?=$this->matter_id?>" id="matter-id" />
</div>
<div id="add-matter-popup"></div>
<div id="actor-details-popup" class="place-card"></div>
<div id="actor-details-used-in" style="z-index: 1; position: fixed; bottom: 0; right: 10px;"></div>
<div id="facade"></div>
